version: 0.2
phases:
  install:
    commands:
      - printenv
      - npm install
  build:
    commands:
      - pwd
      - npm run build
      - ls
  post_build:
    commands:
      - mkdir -p build
      - pwd
      - ls
artifacts:
  files:
    - Dockerfile
    - LICENSE
    - README.md
    - appspec.yml
    - build
    - buildspec.yml
    - docker-compose.yml
    - node_modules
    - package-lock.json
    - package.json
    - public
    - src
    - yarn.lock
  discard-paths: yes
